name: Deploy to ECS - Dev Environment

on:
  pull_request:
    types:
      - closed
    branches:
      - development
env:
  ENVIRONMENT: ${{ github.base.ref }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  ECS_TASK_DEFINITION: infrastructure/development/aws/grafana_task_definition.json
  CONTAINER_NAME: grafana

jobs:
  deploy:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.2.0
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          log-configuration-log-driver: awslogs
          log-configuration-options: |
            awslogs-group=/aws/ecs/aci-ecsserv-grafana-dev-euw1-01
            awslogs-region=eu-west-1
            awslogs-stream-prefix=ecs

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ vars.ECS_SERVICE }}
          cluster: ${{ vars.ECS_CLUSTER }}
          wait-for-service-stability: true
